#!/bin/bash

# Script to clean up all processes - gotten from Josh and edited

#  Cleanup a.out processes
list=`ps -ef | grep imlay_ga | tr -s " " | grep a.out | cut -d " " -f2`

for p in $procs
do
    kill -9 $p 2> /dev/null
done


#  Cleanup user processes
list=`ps -ef | grep imlay_ga | grep user | tr -s " " | cut -d " " -f2`

for p in $procs
do
    kill -9 $p 2> /dev/null
done


#  Cleanup shared memory
list=`ipcs -m | tr -s " " | grep imlay_ga | cut -d " " -f2`
for id in $list
do
    ipcrm -m $id 2> /dev/null
    if [ $? -eq 0 ]; then
        echo "Shared memory segment $id removed successfully."
    else
        echo "Error removing shared memory segment $id."
    fi
done

#  Cleanup semaphores
list=`ipcs -s | tr -s " " | grep imlay_ga | cut -d " " -f2`
for id in $list
do
    ipcrm -s $id 2> /dev/null
    if [ $? -eq 0 ]; then
        echo "Semaphore $id removed successfully."
    else
        echo "Error removing semaphore $id."
    fi
done